travis:
  secure:
    BINSTAR_TOKEN: bW8zFEJuHda5c11iChaI3SeEbXsr0seZShxTd24TJlz7+mCs3gsFUDnDN+F3JvND7i0jZ1Q+ThIpXUmtNLO/IvrnRijiK8iIo0ygSt5A8+lmrHLRuxIyWk69jFBtirOjw7RcZ+AsGQabU33HeiKH/Xqh4kUFsFcPA4kwcsu91sjhRd43nZEfsxKyOt+RRiuHSwDFUv2S3qf+g7UDSqoGf0vhydY1W4ezjIozTXPnxeMJwldibSiavHchupu3e6eV5rkloylRDct22BXHKnqypdmhGxu9z6Mo+RTJImN5q6MLCwOvey0vVXGnavuLUrixhKn4U7c//1OgiPN2974dtY3fePMVOuGDAKc2Kvp4WuqpJivHE9bWePmrSe1WSeae3zHafXphWleii9MoFH3LaGUp19spmOp2oZvBAhNxGe5aBs8JkKQT6RVMQJzSC15vaExQsgGQ+aR2RiDEzwRzIuzlcwN5J7neQ/STZfdIHCMsuENehlKvAy5xtYvc+uJbPBYZZfok0/YUmVQCtMmkUBQEHIg3OQzvQj3GDAfCy1/GiNn9PGmywj1omAtduVdbZA7WIPDG5c04Td7WytS2CrSB7Nm62G9DPJ7xrrdaCSTYC3YqE9YsG8puyA8p9zOAFlLF88vX9iVL3moOnyf+ikA4s9fUgjcm7WYmr3c9KQ8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
